### ISSUE TITLE
gitgraph.lua:987: assertion failed!

### ISSUE THREAD

**Issue by kdheepak** [isakbm/gitgraph.nvim#15]
Thanks for making this plugin!

I wanted to report that I get the following error when I try to clone <https://github.com/ratatui-org/ratatui> and run gitgraph:

```
E5108: Error executing lua: .../.local/share/nvim/lazy/gitgraph.nvim/lua/gitgraph.lua:987: assertion failed!
stack traceback:
        [C]: in function 'assert'
        .../.local/share/nvim/lazy/gitgraph.nvim/lua/gitgraph.lua:987: in function 'commit_cell_symb'
        .../.local/share/nvim/lazy/gitgraph.nvim/lua/gitgraph.lua:1012: in function 'row_to_str'
        .../.local/share/nvim/lazy/gitgraph.nvim/lua/gitgraph.lua:1150: in function 'gitgraph'
        .../.local/share/nvim/lazy/gitgraph.nvim/lua/gitgraph.lua:1851: in function 'draw'
        /Users/USERNAME/.config/nvim/lua/kd/plugins/git-graph.lua:29: in function </Users/USERNAME/.config/nvim/lua/kd/plugins/git-graph.lua:28>
Press ENTER or type command to continue
```

**Comment by Xouzoura** [comment]
Same here for me in ubuntu

**Comment by isakbm** [comment]
Thank you.

Will try to reproduce this and get to the bottom of it.

**Comment by isakbm** [comment]
Was able to reproduce this, btw that repo looks amazing :) <3 Rust

**Comment by isakbm** [comment]
This is an interesting bug, it seems related to a branch called `(origini/images)`, ... gitgraph tries to render this branch, but perhaps this branch has no common ancestors with the other branches 🤔 

With `git log --graph --oneline --all`, I am unable to find the branch `origin/images` ...

**Comment by isakbm** [comment]
Oh cool, I think I figured out what it is.

Commit `6754f92` has no parents, so has no ancestors in common with the rest of the repo. I just never considered handling this case. I'll probably have a fix in today. BTW `git log --graph --oneline --dateorder` shows this, but `git log --graph --oneline`  show ssomething quite confusing.

![image](https://github.com/user-attachments/assets/6817d3ee-b564-4714-9325-af2b3b2b30df)

![image](https://github.com/user-attachments/assets/66f8afe3-cf84-455b-8a3a-de67fb7ab672)

So at least gitgraph is failing rather than trying to show something confusing :)

Will be great to have this fixed though! 🎉 

Diving deeper now

**Comment by isakbm** [comment]
Should now be fixed, please git it a try 🤞  

Thanks again for reporting this, this is what makes open source so great!

**Comment by kdheepak** [comment]
Yay! Thanks for the quick fix! Works perfectly for me now!
